/* Private key of the TCP client generated by OpenSSL */
#define CLIENT_PRIVATE_KEY_PEM \
"-----BEGIN EC PRIVATE KEY-----\n"\
"MHcCAQEEIEBGIdEovAXfGF0NSXVk2edqcRByeF4KUJ8Pe/Qhxig9oAoGCCqGSM49\n"\
"AwEHoUQDQgAE3esUSnUXeJJEeMXkJnBAYOZeoC8UMYotrrt+eyH8Eua3hDEgarNa\n"\
"4/ynPzMfMAchgrhlFq4gT7F3yGFczTW5ew==\n"\
"-----END EC PRIVATE KEY-----\n"
