/* Private key of the TCP Server generated by OpenSSL */
#define SERVER_PRIVATE_KEY_PEM \
"-----BEGIN EC PRIVATE KEY-----\n"\
"MHcCAQEEIMmEMlmaTHOF12k3/wzcalsX8ENSmdfJLXEP+8w6ljD2oAoGCCqGSM49\n"\
"AwEHoUQDQgAEcNIiKXt9FRegfYMHrQLYKhXNFJnDUP/94Ek/f0T0uC2a+isDfhWn\n"\
"Yb6Waym4RF0/YzvCkwlbbTp7qNTvNTMCjQ==\n"\
"-----END EC PRIVATE KEY-----\n"
