/******************************************************************************
* File Name:   tcp_server.h
*
* Description: This file contains declaration of task and functions related to
* TCP server operation.
*
*******************************************************************************
* (c) 2020, Cypress Semiconductor Corporation. All rights reserved.
*******************************************************************************
* This software, including source code, documentation and related materials
* ("Software"), is owned by Cypress Semiconductor Corporation or one of its
* subsidiaries ("Cypress") and is protected by and subject to worldwide patent
* protection (United States and foreign), United States copyright laws and
* international treaty provisions. Therefore, you may use this Software only
* as provided in the license agreement accompanying the software package from
* which you obtained this Software ("EULA").
*
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software source
* code solely for use in connection with Cypress's integrated circuit products.
* Any reproduction, modification, translation, compilation, or representation
* of this Software except as specified above is prohibited without the express
* written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death ("High Risk Product"). By
* including Cypress's product in a High Risk Product, the manufacturer of such
* system or application assumes all risk of such use and in doing so agrees to
* indemnify Cypress against all liability.
*******************************************************************************/

#ifndef TCP_SERVER_H_
#define TCP_SERVER_H_

/*******************************************************************************
* Macros
********************************************************************************/
/* Wi-Fi Credentials: Modify WIFI_SSID, WIFI_PASSWORD, and WIFI_SECURITY_TYPE
 * to match your Wi-Fi network credentials.
 * Note: Maximum length of the Wi-Fi SSID and password is set to
 * CY_WCM_MAX_SSID_LEN and CY_WCM_MAX_PASSPHRASE_LEN as defined in cy_wcm.h file.
 */
#define WIFI_SSID                                 "ssid"
#define WIFI_PASSWORD                             "pswd"

/* Security type of the Wi-Fi access point. See 'cy_wcm_security_t' structure
 * in "cy_wcm.h" for more details.
 */
#define WIFI_SECURITY_TYPE                        CY_WCM_SECURITY_WPA2_AES_PSK

/* Maximum number of connection retries to a Wi-Fi network. */
#define MAX_WIFI_CONN_RETRIES                     (10u)

/* Wi-Fi re-connection time interval in milliseconds */
#define WIFI_CONN_RETRY_INTERVAL_MSEC             (1000)

/* TCP server related macros. */
#define TCP_SERVER_PORT                           (40508)
#define TCP_SERVER_MAX_PENDING_CONNECTIONS        (3)
#define TCP_SERVER_RECV_TIMEOUT_MS                (4000)
#define MAX_TCP_RECV_BUFFER_SIZE                  (20)
#define MAX_TCP_DATA_PACKET_LENGTH				  (20)

/* TCP server certificate. Copy from the TCP server certificate
 * generated by OpenSSL (See Readme.md on how to generate a SSL certificate).
 */
#define keySERVER_CERTIFICATE_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIIDYTCCAkmgAwIBAgIJAKesn3EKnL30MA0GCSqGSIb3DQEBCwUAMEcxCzAJBgNV\n"\
"BAYTAlVTMREwDwYDVQQIDAhLZW50dWNreTESMBAGA1UEBwwJTGV4aW5ndG9uMREw\n"\
"DwYDVQQKDAhJbmZpbmVvbjAeFw0yMTA5MjkxNDM0MDFaFw0zMTA5MjcxNDM0MDFa\n"\
"MEcxCzAJBgNVBAYTAlVTMREwDwYDVQQIDAhLZW50dWNreTESMBAGA1UEBwwJTGV4\n"\
"aW5ndG9uMREwDwYDVQQKDAhJbmZpbmVvbjCCASIwDQYJKoZIhvcNAQEBBQADggEP\n"\
"ADCCAQoCggEBALQ50t6GQze9Uekak0kU9prdEjDf2AfICo8hem8MvTEw74yQMljL\n"\
"puuzwRCxPIUCkJiezUH0VwlT0OSAlPjn19r/hLUDmcKfUTIwM8ei6YaN8hZy38Hc\n"\
"py41f9V2ExUY6fTWGLhKXakEbZRq2b2dPf6dM0PVFkdC8PgAoQ+0fYe+UwPFmDqS\n"\
"++qyOpNo0U/0CMWe3HjNYbeQlZRnJr/XKnmmhNmXBTG+57rN/svfpIN6gv3SMtcg\n"\
"IAAYd1az9dgybR07Sz7q9Ah8TNWy8zDH0x8BVW7psH0ONaK73VtWhU7z61/XpPse\n"\
"GEBzaLdikOO0TmlmQrVVQKpLvO34H90qUMECAwEAAaNQME4wHQYDVR0OBBYEFLas\n"\
"AabpF/zmkBrXdA708JCL2TgdMB8GA1UdIwQYMBaAFLasAabpF/zmkBrXdA708JCL\n"\
"2TgdMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAE7Za3HZcSxbnKtl\n"\
"b3yqRLkDvciy0EfqGk7l6y0MN75wcN27rHMCSKRJ9tRJl1XSlSrPx/y3qD15yF0f\n"\
"YGTJoKNjrRgvuyfKUipjCh8GqK7dGalJ1FstR9v5xiaDLx1bPwaVm4jUCkEdeyUk\n"\
"lsKxYECls2RbyVMMtxSGTzkUMt1S/PWpTk1t/yOv3THPsToFS/clxkMBeqzloP1T\n"\
"egnrv+GkCWYu9Mp6PnfZQR2sWxyUu+BvVwSBiekY6Vez8RUIQ/D2vMB+tRrJfR89\n"\
"awk0docPF/I4nboELq8hP4lxaPNPZGj5syqNxXB267ywsT6YRjcYteUN+h97X0Fm\n"\
"BKicZts=\n"\
"-----END CERTIFICATE-----\n"

/* Private key of the TCP Server. Copy from the TCP server key
 * generated by OpenSSL (See Readme.md on how to create a private key).
 */
#define keySERVER_PRIVATE_KEY_PEM \
"-----BEGIN PRIVATE KEY-----\n"\
"MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC0OdLehkM3vVHp\n"\
"GpNJFPaa3RIw39gHyAqPIXpvDL0xMO+MkDJYy6brs8EQsTyFApCYns1B9FcJU9Dk\n"\
"gJT459fa/4S1A5nCn1EyMDPHoumGjfIWct/B3KcuNX/VdhMVGOn01hi4Sl2pBG2U\n"\
"atm9nT3+nTND1RZHQvD4AKEPtH2HvlMDxZg6kvvqsjqTaNFP9AjFntx4zWG3kJWU\n"\
"Zya/1yp5poTZlwUxvue6zf7L36SDeoL90jLXICAAGHdWs/XYMm0dO0s+6vQIfEzV\n"\
"svMwx9MfAVVu6bB9DjWiu91bVoVO8+tf16T7HhhAc2i3YpDjtE5pZkK1VUCqS7zt\n"\
"+B/dKlDBAgMBAAECggEAIihXa+9cbAMItDpiMda0SnOdz/+MzSS/w5Lfxo5OiTUy\n"\
"IZzuvd+TOlbuP4Cn7LmouBRY6Kgrmsv06mnoUih2w73r4/bTvIw/cliqZ6rbwbHD\n"\
"cTfCatasJNjk6osfYL9BEDNHqh4GFFOPhTKfJA3aQxh+L9wCBe2NCCPuYrCdng1F\n"\
"j/Ynj9oR9DHLv3/vDoLHaiHKNygSrE7aYkxrukwB4Ly4GRDG9elyHI7Cd9Lz88yt\n"\
"L7Gx4EcZRfNXfdW0Hhw2+YI7jALMqK3JEMfX3XQA2/HrRgPWjdHAlAnYIJDicGfS\n"\
"O33V84O8uYAOnTOrtO7c+5CfgxDJZqA3ZhVavSvPpQKBgQDtdB8/gIvrz93k5vJE\n"\
"PxacupfkgJxZCrS42xY9BKbREqG2viMXLKsJrME8bW6orvEMX+w8TDOhtziua6X4\n"\
"avhFINA/JDZPTk4q6kV2WH0AMFEn5zZPztELnerDO2qkId50Pviemz4eM2YIqqgs\n"\
"iz01WeZz1GasHg3/lPMlUMqG0wKBgQDCTW9Tt98AJaJlrofaKOEXmszXLf+8151B\n"\
"LNcwNBgWXM3sY11XI3goC66sQz9rr+uRhrGPXkhSPVHafr5k5NzkneUuuXrb7qpV\n"\
"zfo+D1hRNmVWZs3uu8tODMN+8Q2uKOUEocl1Gy/10ixZnS30oCLNvelPePJyBGLg\n"\
"+ggoBjs1mwKBgQClE5p5sisT+AGiFbANI/LbaJkaIRMQj/HNpXnTV72FEbfc7FhG\n"\
"zyXk5vW7xbQtjtlDKhh4Xt1yKoc8MthCWFNa85Hyo4EiJyUOjqlVufTEwdJZtFK8\n"\
"ruIDenhv24mqq2UUWYbL9M79fewMUF/z/6TAx0v/8ISkWYyPxwQ2R/FUQwKBgH1P\n"\
"6ZvJu1Xh78G6dT17HejWWoPw073cJTxyifo5rstFYT2yu/FGG+lf13CcElwGYlxB\n"\
"zWRUfzoi+BZ9pZd2jwwW1Ud0MkuDunGKXXkG9oOyHFtEBE6S6UTWMIM/Pf5zu3ho\n"\
"S4BuX1kgCqBlIc1iNfARKlap/1sPfyHvv7Doi+k/AoGBAKh5uL0yDysixC1BGM8w\n"\
"lyhaZlH94oq3FUV73hGqLdHKL09zhM9hPNj/w8HqmBNBbg6cPaSmLatGkeQMFkbL\n"\
"y89YIzFqb/G6uWDYOkaBFVclMXBpbFreHGUiGZbbuXS2bLruWZty8F+xkgFVUmbr\n"\
"rTGIeI/5wNczpdx4YRJm/i9Q\n"\
"-----END PRIVATE KEY-----\n"

/* TCP client certificate. In this example this is the RootCA
 * certificate so as to verify the TCP client's identity. */
#define keyCLIENT_ROOTCA_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIIDYTCCAkmgAwIBAgIJAJ5yTQtF1tSRMA0GCSqGSIb3DQEBCwUAMEcxCzAJBgNV\n"\
"BAYTAlVTMREwDwYDVQQIDAhLZW50dWNreTESMBAGA1UEBwwJTGV4aW5ndG9uMREw\n"\
"DwYDVQQKDAhJbmZpbmVvbjAeFw0yMTA5MjkxNDE3MDVaFw0zMTA5MjcxNDE3MDVa\n"\
"MEcxCzAJBgNVBAYTAlVTMREwDwYDVQQIDAhLZW50dWNreTESMBAGA1UEBwwJTGV4\n"\
"aW5ndG9uMREwDwYDVQQKDAhJbmZpbmVvbjCCASIwDQYJKoZIhvcNAQEBBQADggEP\n"\
"ADCCAQoCggEBALN+B6rq8MICPtidqT+c315fCBFJSZlYqF0Fh/LwqNsirkKdm9pC\n"\
"Q6ofG6rKh+BBahpdUyqfF6pw2k7Is9CsnWkObDjQLepipwD2YKqeP580y6/nFuBe\n"\
"ZjYe58fnjFGN8M59IC/Ny3N2l4vAUbz9wGdYhAmAMMpg4Ye1CEcfYNXcrWHE4VYE\n"\
"RvRJWUUgD2rc1Ef21jt37DfkNH4fRAN2OKt3BiC+05yZbZV50GqOAfr8N0pQSjxb\n"\
"KUzrRYuYIWFX7k4EHn2MeV54OQCY6Nnxnf4l2VlTOBUgd+mHPSAs7+SMTKIrc07d\n"\
"MMGM11DIK16FjuhhIUGlzPuoSmIzBS/YdxECAwEAAaNQME4wHQYDVR0OBBYEFAaa\n"\
"qOwW9cZnFSiNAtXI7Qt9x72mMB8GA1UdIwQYMBaAFAaaqOwW9cZnFSiNAtXI7Qt9\n"\
"x72mMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAEd2j6RvIGZL8Dt2\n"\
"auIrzedTs0DDlZONLAdadO66MyxYjDXY6BRuIRMiE/VJhz4yDlfx8sCy/NXnyXBJ\n"\
"JQ3OR2x3oklYWutDtE5H8PtaBcKVIaW4/mKboTaqTh/ndwYfcZ59+QRAZEl24L0u\n"\
"hKu+0le24Jrn8TYmxkahwWOBe32kM0F/RabyPKDOZfrKt/WLCHvk7BlTfjqhgGcO\n"\
"y/396INavo35b0rmcBXBWAt0WItyrXNfq25icdZr21vtX5+Uji5YbnUUhgBOSj5d\n"\
"YXrP4BzzgMeB9ws8RPf/auKVMyQjbsSAgcLxS3IE10Zrh/keUL/CT/D7C2VqfDr3\n"\
"oWMMkmw=\n"\
"-----END CERTIFICATE-----\n"

/*******************************************************************************
* Function Prototypes
********************************************************************************/
void tcp_server_task(void *arg);

#endif /* TCP_SERVER_H_ */
