/* Private key of the TCP Server. Copy from the TCP server key
 * generated by OpenSSL (See Readme.md on how to create a private key).
 */
#define keySERVER_PRIVATE_KEY_PEM \
"-----BEGIN PRIVATE KEY-----\n"\
"MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC0OdLehkM3vVHp\n"\
"GpNJFPaa3RIw39gHyAqPIXpvDL0xMO+MkDJYy6brs8EQsTyFApCYns1B9FcJU9Dk\n"\
"gJT459fa/4S1A5nCn1EyMDPHoumGjfIWct/B3KcuNX/VdhMVGOn01hi4Sl2pBG2U\n"\
"atm9nT3+nTND1RZHQvD4AKEPtH2HvlMDxZg6kvvqsjqTaNFP9AjFntx4zWG3kJWU\n"\
"Zya/1yp5poTZlwUxvue6zf7L36SDeoL90jLXICAAGHdWs/XYMm0dO0s+6vQIfEzV\n"\
"svMwx9MfAVVu6bB9DjWiu91bVoVO8+tf16T7HhhAc2i3YpDjtE5pZkK1VUCqS7zt\n"\
"+B/dKlDBAgMBAAECggEAIihXa+9cbAMItDpiMda0SnOdz/+MzSS/w5Lfxo5OiTUy\n"\
"IZzuvd+TOlbuP4Cn7LmouBRY6Kgrmsv06mnoUih2w73r4/bTvIw/cliqZ6rbwbHD\n"\
"cTfCatasJNjk6osfYL9BEDNHqh4GFFOPhTKfJA3aQxh+L9wCBe2NCCPuYrCdng1F\n"\
"j/Ynj9oR9DHLv3/vDoLHaiHKNygSrE7aYkxrukwB4Ly4GRDG9elyHI7Cd9Lz88yt\n"\
"L7Gx4EcZRfNXfdW0Hhw2+YI7jALMqK3JEMfX3XQA2/HrRgPWjdHAlAnYIJDicGfS\n"\
"O33V84O8uYAOnTOrtO7c+5CfgxDJZqA3ZhVavSvPpQKBgQDtdB8/gIvrz93k5vJE\n"\
"PxacupfkgJxZCrS42xY9BKbREqG2viMXLKsJrME8bW6orvEMX+w8TDOhtziua6X4\n"\
"avhFINA/JDZPTk4q6kV2WH0AMFEn5zZPztELnerDO2qkId50Pviemz4eM2YIqqgs\n"\
"iz01WeZz1GasHg3/lPMlUMqG0wKBgQDCTW9Tt98AJaJlrofaKOEXmszXLf+8151B\n"\
"LNcwNBgWXM3sY11XI3goC66sQz9rr+uRhrGPXkhSPVHafr5k5NzkneUuuXrb7qpV\n"\
"zfo+D1hRNmVWZs3uu8tODMN+8Q2uKOUEocl1Gy/10ixZnS30oCLNvelPePJyBGLg\n"\
"+ggoBjs1mwKBgQClE5p5sisT+AGiFbANI/LbaJkaIRMQj/HNpXnTV72FEbfc7FhG\n"\
"zyXk5vW7xbQtjtlDKhh4Xt1yKoc8MthCWFNa85Hyo4EiJyUOjqlVufTEwdJZtFK8\n"\
"ruIDenhv24mqq2UUWYbL9M79fewMUF/z/6TAx0v/8ISkWYyPxwQ2R/FUQwKBgH1P\n"\
"6ZvJu1Xh78G6dT17HejWWoPw073cJTxyifo5rstFYT2yu/FGG+lf13CcElwGYlxB\n"\
"zWRUfzoi+BZ9pZd2jwwW1Ud0MkuDunGKXXkG9oOyHFtEBE6S6UTWMIM/Pf5zu3ho\n"\
"S4BuX1kgCqBlIc1iNfARKlap/1sPfyHvv7Doi+k/AoGBAKh5uL0yDysixC1BGM8w\n"\
"lyhaZlH94oq3FUV73hGqLdHKL09zhM9hPNj/w8HqmBNBbg6cPaSmLatGkeQMFkbL\n"\
"y89YIzFqb/G6uWDYOkaBFVclMXBpbFreHGUiGZbbuXS2bLruWZty8F+xkgFVUmbr\n"\
"rTGIeI/5wNczpdx4YRJm/i9Q\n"\
"-----END PRIVATE KEY-----\n"
